---
- name: Create server list file that contains all inventory hosts on databse host group
  hosts: database
  tasks:
    - name: Create server list file from template
      ansible.builtin.template:
        src: ./server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: '0600'
        setype: net_conf_t
      become: true